# Generated by Django 3.1.7 on 2021-03-24 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0002_auto_20210324_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本手机号码(不加-)', regex='^0[789]0-[0-9]{4}-[0-9]{4}$')], verbose_name='发件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_addr',
            field=models.CharField(default='0', max_length=200, verbose_name='收件人详细地址'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_city',
            field=models.CharField(default='0', max_length=200, verbose_name='收件人市'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_district',
            field=models.CharField(default='0', max_length=200, verbose_name='收件人区（县）'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_id',
            field=models.CharField(default='0', max_length=15, validators=[django.core.validators.RegexValidator(message='请输入正确的身份证号', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='收件人身份证号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_name',
            field=models.CharField(default='0', max_length=200, verbose_name='收件人姓名'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_phone_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本电话号码(不加-)', regex='^0([0-9]-[0-9]{4}|[0-9]{2}-[0-9]{3}|[0-9]{3}-[0-9]{2}|[0-9]{4}-[0-9])-[0-9]{4}$')], verbose_name='收件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_province',
            field=models.CharField(default='0', max_length=200, verbose_name='收件人省'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_phone_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本电话号码(不加-)', regex='^0([0-9]-[0-9]{4}|[0-9]{2}-[0-9]{3}|[0-9]{3}-[0-9]{2}|[0-9]{4}-[0-9])-[0-9]{4}$')], verbose_name='发件人电话号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_num',
            field=models.CharField(default='0', max_length=200, verbose_name='发件人微信号'),
        ),
        migrations.AlterField(
            model_name='express',
            name='track_number',
            field=models.CharField(default='0', max_length=200, verbose_name='快递单号'),
        ),
    ]
