# Generated by Django 3.1.7 on 2021-03-24 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0005_auto_20210324_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='sender_phone_num',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='请输入日本电话号码(不加-)', regex='^0([0-9][0-9]{4}|[0-9]{2}[0-9]{3}|[0-9]{3}[0-9]{2}|[0-9]{4}[0-9])[0-9]{4}$')], verbose_name='发件人电话号码'),
        ),
    ]
