# Generated by Django 3.1.7 on 2021-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0006_auto_20210324_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发件人姓名'),
        ),
    ]
