# Generated by Django 3.1.7 on 2021-03-24 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0007_auto_20210324_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='recipient_id',
            field=models.CharField(default='0', max_length=200, validators=[django.core.validators.RegexValidator(message='请输入正确的身份证号', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='收件人身份证号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_phone_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入中国手机号码', regex='^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})d{8}$')], verbose_name='收件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_phone_num',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='请输入日本电话号码(不加-)', regex='^0([0-9][0-9]{4}|[0-9]{2}[0-9]{3}|[0-9]{3}[0-9]{2}|[0-9]{4}[0-9])[0-9]{4}$')], verbose_name='发件人电话号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发件人微信名字'),
        ),
        migrations.AlterField(
            model_name='express',
            name='track_number',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='快递单号'),
        ),
    ]
