# Generated by Django 3.1.7 on 2021-03-24 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0008_auto_20210324_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='recipient_phone_num',
            field=models.CharField(default='0', max_length=200, validators=[django.core.validators.RegexValidator(message='请输入中国手机号码', regex='^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='收件人手机号码'),
        ),
    ]
