# Generated by Django 3.1.7 on 2021-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0009_auto_20210324_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='express',
            name='sender_phone_num',
        ),
    ]
