# Generated by Django 3.1.7 on 2021-03-28 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0010_remove_express_sender_phone_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='express',
            options={'verbose_name': '快递订单', 'verbose_name_plural': '快递订单'},
        ),
        migrations.AddField(
            model_name='express',
            name='shop',
            field=models.CharField(max_length=200, null=True, verbose_name='寄件店铺'),
        ),
        migrations.AlterField(
            model_name='express',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='寄件日期时间'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本手机号码(不加-)', regex='^0[789]0[0-9]{4}[0-9]{4}$')], verbose_name='寄件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='寄件人姓名'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='寄件人微信名字'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_num',
            field=models.CharField(default='0', max_length=200, verbose_name='寄件人微信号'),
        ),
        migrations.AlterField(
            model_name='express',
            name='track_number',
            field=models.CharField(blank=True, default='xxx', max_length=200, verbose_name='快递单号'),
        ),
    ]
