# Generated by Django 3.1.7 on 2021-03-28 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0011_auto_20210328_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='recipient_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='收件人身份证照片上传'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='请输入日本手机号码(不加-)', regex='^0[789]0[0-9]{4}[0-9]{4}$')], verbose_name='寄件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_num',
            field=models.CharField(default='0', max_length=200, verbose_name='寄件人微信号(必填)'),
        ),
    ]
