# Generated by Django 3.1.7 on 2021-03-29 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0012_auto_20210328_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='请输入日本或中国手机号码(不加-)', regex='(^0[789]0[0-9]{4}[0-9]{4}$)|^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='寄件人手机号码'),
        ),
    ]
