# Generated by Django 3.1.7 on 2021-04-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0013_auto_20210329_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='寄件人姓名(选填)'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='寄件人微信名字(选填)'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_num',
            field=models.CharField(default='0', max_length=200, verbose_name='寄件人微信号'),
        ),
    ]
