# Generated by Django 3.1.7 on 2021-04-02 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0014_auto_20210402_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本或中国手机号码(不加-)', regex='(^0[789]0[0-9]{4}[0-9]{4}$)|^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='寄件人手机号码'),
        ),
    ]
