# Generated by Django 3.1.7 on 2021-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0015_auto_20210402_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='track_number',
            field=models.CharField(blank=True, default='0', max_length=200, verbose_name='快递单号'),
        ),
    ]
