# Generated by Django 3.1.7 on 2021-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0016_auto_20210402_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='packet_state',
            field=models.BooleanField(blank=True, default=False, verbose_name='包裹状态'),
        ),
        migrations.AlterField(
            model_name='express',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='寄件时间'),
        ),
    ]
