# Generated by Django 3.1.7 on 2021-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0018_auto_20210402_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='packet_state',
            field=models.CharField(blank=True, default='未发送', max_length=20, verbose_name='包裹状态'),
        ),
        migrations.AlterField(
            model_name='express',
            name='track_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='快递单号'),
        ),
    ]
