# Generated by Django 3.1.7 on 2021-04-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0020_auto_20210404_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='recipient_photo',
            field=models.ImageField(blank=True, upload_to='recipient_photo/%Y/%m/%d/', verbose_name='收件人身份证照片上传'),
        ),
    ]
