# Generated by Django 3.1.7 on 2021-04-04 02:04

from django.db import migrations, models
import etrack.models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0021_auto_20210404_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='recipient_photo',
            field=models.ImageField(blank=True, upload_to=etrack.models.user_photo_path, verbose_name='收件人身份证照片上传'),
        ),
    ]
