# Generated by Django 3.1.7 on 2021-04-04 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0022_auto_20210404_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发件登录时间'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(default='0', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本或中国手机号码(不加-)', regex='(^0[789]0[0-9]{4}[0-9]{4}$)|^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='发件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发件人姓名(选填)'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发件人微信名字(选填)'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_num',
            field=models.CharField(default='0', max_length=200, verbose_name='发件人微信号'),
        ),
        migrations.AlterField(
            model_name='express',
            name='shop',
            field=models.CharField(max_length=200, null=True, verbose_name='发件店铺'),
        ),
    ]
