# Generated by Django 3.1.7 on 2021-04-04 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0023_auto_20210404_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='recipient_addr',
            field=models.CharField(default='', max_length=200, verbose_name='收件人详细地址'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_city',
            field=models.CharField(default='', max_length=200, verbose_name='收件人市'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_district',
            field=models.CharField(default='', max_length=200, verbose_name='收件人区（县）'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_id',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='请输入正确的身份证号', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='收件人身份证号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_name',
            field=models.CharField(default='', max_length=200, verbose_name='收件人姓名'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_phone_num',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='请输入中国手机号码', regex='^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='收件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_province',
            field=models.CharField(default='', max_length=200, verbose_name='收件人省'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_mobile_num',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message='请输入日本或中国手机号码(不加-)', regex='(^0[789]0[0-9]{4}[0-9]{4}$)|^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='发件人手机号码'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_num',
            field=models.CharField(default='', max_length=200, verbose_name='发件人微信号'),
        ),
    ]
