# Generated by Django 3.1.7 on 2021-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0024_auto_20210404_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发件人姓名(选填)'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发件人微信名字(选填)'),
        ),
    ]
