# Generated by Django 3.1.7 on 2021-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0025_auto_20210404_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='agent_account',
            field=models.CharField(default='ZZagent', max_length=200, verbose_name='代理人账号'),
        ),
    ]
