# Generated by Django 3.1.7 on 2021-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0026_express_agent_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='express',
            name='auto_recipient_name',
            field=models.CharField(default='', max_length=200, verbose_name='散客名称'),
        ),
        migrations.AddField(
            model_name='express',
            name='sender_address',
            field=models.CharField(default='〒 332-0016埼玉県川口市幸町1-14-10', max_length=200, verbose_name='发件人地址'),
        ),
        migrations.AddField(
            model_name='express',
            name='sender_city',
            field=models.CharField(default='川口市', max_length=200, verbose_name='发件人市'),
        ),
        migrations.AddField(
            model_name='express',
            name='sender_country',
            field=models.CharField(default='日本', max_length=200, verbose_name='发件人国家'),
        ),
        migrations.AddField(
            model_name='express',
            name='sender_district',
            field=models.CharField(default='幸町', max_length=200, verbose_name='发件人区（县）'),
        ),
        migrations.AddField(
            model_name='express',
            name='sender_province',
            field=models.CharField(default='埼玉县', max_length=200, verbose_name='发件人省'),
        ),
    ]
