# Generated by Django 3.1.7 on 2021-05-24 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrack', '0027_auto_20210404_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发件人登录时间'),
        ),
        migrations.AlterField(
            model_name='express',
            name='recipient_phone_num',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(message='请输入中国手机号码', regex='^(13[0-9]|14[01456879]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[0-3,5-9]{3})[0-9]{8}$')], verbose_name='收件人手机'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发件人姓名（选填）'),
        ),
        migrations.AlterField(
            model_name='express',
            name='sender_wechat_name',
            field=models.CharField(default='', max_length=200, verbose_name='发件人微信名字'),
        ),
    ]
